package com.rdf.metadata.sql.filter;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.List;

/**
 * A single WHERE clause predicate: {@code column operator value(s)}.
 *
 * <h3>Value rules by operator</h3>
 * <table border="1">
 *   <tr><th>Operator</th><th>Field to set</th><th>Example</th></tr>
 *   <tr><td>EQ, NEQ, GT, GTE, LT, LTE, LIKE, NOT_LIKE, ILIKE</td>
 *       <td>{@code value}</td>
 *       <td>{@code {"column":"STATUS","operator":"EQ","value":"ACTIVE"}}</td></tr>
 *   <tr><td>IN, NOT_IN</td>
 *       <td>{@code values}</td>
 *       <td>{@code {"column":"STATUS","operator":"IN","values":["ACTIVE","PENDING"]}}</td></tr>
 *   <tr><td>BETWEEN, NOT_BETWEEN</td>
 *       <td>{@code value} (lower) + {@code valueTo} (upper)</td>
 *       <td>{@code {"column":"TOTAL_AMOUNT","operator":"BETWEEN","value":"100","valueTo":"500"}}</td></tr>
 *   <tr><td>IS_NULL, IS_NOT_NULL</td>
 *       <td><i>none</i></td>
 *       <td>{@code {"column":"DELETED_AT","operator":"IS_NULL"}}</td></tr>
 * </table>
 */
@Data
public class FilterCriterion {

    /** The column name to filter on — must match a column in the target table's SHACL shape. */
    @NotBlank(message = "column is required")
    private String column;

    /** The comparison operator. */
    @NotNull(message = "operator is required")
    private FilterOperator operator;

    /**
     * Single scalar value — used by EQ, NEQ, GT, GTE, LT, LTE, LIKE, NOT_LIKE, ILIKE.
     * Also the lower bound for BETWEEN / NOT_BETWEEN.
     */
    private String value;

    /**
     * Upper bound for BETWEEN / NOT_BETWEEN.
     * Ignored for all other operators.
     */
    private String valueTo;

    /**
     * List of values for IN / NOT_IN operators.
     * Must contain at least one entry when operator is IN or NOT_IN.
     */
    private List<String> values;

    /**
     * Named parameter key used in the generated SQL for this criterion's {@code value}.
     * Auto-generated by the builder as {@code <column>_<index>} to avoid name collisions
     * when the same column appears more than once in a filter group.
     * Not set by the caller — populated internally.
     */
    private String paramKey;
}
